_infra/helm/Chart.yaml
_infra/helm/templates/deployment.yaml
config.go
go.mod
go.sum
info.go
info_test.go
main.go
main_test.go
models/error.go
respondents.go
respondents_test.go

Unit test improvements and start of GET /respondents

---

_infra/helm/Chart.yaml
_infra/helm/templates/deployment.yaml
config.go

Remove SSL from Postgres connection

---

_infra/helm/Chart.yaml
models/respondents.go
respondents.go
respondents_test.go

Get respondents 1902

---

_infra/helm/Chart.yaml
config.go
main.go
respondents.go
respondents_test.go
swagger2.yaml

End of GET /respondents

---

_infra/helm/Chart.yaml
main.go
models/respondents.go
respondents.go
respondents_test.go

Post respondents 2020

---

respondents.go
respondents_test.go

More unit tests

---

_infra/helm/Chart.yaml

[x] Helm version updated (`_infra\helm\Chart.yaml`) (for real this time)

Forgot to increment version in the last PR

---

_infra/helm/Chart.yaml
config.go
go.mod
go.sum
models/iac.go
respondents.go
respondents_test.go

More POST /respondent unit tests

---

_infra/helm/partyv2/Chart.yaml
config.go
go.mod
go.sum
main_test.go
models/case.go
models/collectionexercise.go
respondents.go
respondents_test.go

Final parts of POST /respondent

---

_infra/helm/partyv2/Chart.yaml
respondents.go
respondents_test.go

Actual end of POST /respondent

---

_infra/helm/partyv2/Chart.yaml
go.mod

Upgarding to Go 1.14 and seeing what breaks

---

_infra/helm/partyv2/Chart.yaml
respondents.go
respondents_test.go

Finishing DELETE /respondent

---

_infra/helm/partyv2/Chart.yaml
main.go
respondents.go
respondents_test.go

GET /respondents/{id}

---

_infra/helm/partyv2/Chart.yaml
main.go
respondents.go
respondents_test.go

Start of PATCH /respondents/{id}

---

_infra/helm/partyv2/Chart.yaml
_infra/helm/partyv2/templates/deployment.yaml

Fix issue with healthcheck

---

_infra/helm/partyv2/Chart.yaml
_infra/helm/partyv2/templates/deployment.yaml

Making sure port is in the right format

---

_infra/helm/partyv2/Chart.yaml
respondents.go

Get respondent bug fix

---

_infra/helm/partyv2/Chart.yaml
_infra/helm/partyv2/templates/deployment.yaml

Add protocol in front of config

---

_infra/helm/partyv2/Chart.yaml
respondents.go
respondents_test.go

Patch respondent by ID cont.

---

_infra/helm/partyv2/Chart.yaml
respondents.go
respondents_test.go
swagger2.yaml

Continuation of PATCH /respondents/{id}

---

_infra/helm/partyv2/Chart.yaml
basiclistener.go
main.go

Creating a basic listener to reduce debug info in production

---

_infra/helm/partyv2/Chart.yaml
_infra/helm/partyv2/templates/deployment.yaml

Readding the ssl disable

---

_infra/helm/partyv2/Chart.yaml
_infra/helm/partyv2/templates/deployment.yaml

Add DNS entries to Helm config

---

_infra/helm/partyv2/Chart.yaml
_infra/helm/partyv2/values.yaml

Add values missed off from DNS work

---

_infra/helm/partyv2/Chart.yaml
_infra/helm/partyv2/templates/deployment.yaml

[] Helm version updated (`_infra\helm\Chart.yaml`)

Fix the kubernetes deployment

---

.github/workflows/main.yml
Dockerfile
_infra/helm/partyv2/Chart.yaml

[] Helm version updated (`_infra\helm\Chart.yaml`)

Add GitHub actions

---

.github/workflows/main.yml

replace concourse by updating appVersion, creating a release container, a dev container and publishing the helm chart on merge

replace concourse entirely

---

.github/workflows/comment.yml
.github/workflows/main.yml
_infra/helm/partyv2/Chart.yaml

[] Helm version updated (`_infra\helm\Chart.yaml`)

Make dev docker tag changes

---

.github/workflows/comment.yml
.github/workflows/main.yml
_infra/helm/partyv2/Chart.yaml

[] Helm version updated (`_infra\helm\Chart.yaml`)

fix action
